/* CRIAR BANCO DE DADOS */
CREATE DATABASE CRUD

/* SELECIONA O BANCO DE DADOS */
USE CRUD

/* CRIACÇÃO DA TABELA */
CREATE TABLE CLIENTE (
      ID INT NOT NULL IDENTITY,
      NOME VARCHAR(50)  NOT NULL,
      ENDERECO VARCHAR(50),
      CEP VARCHAR(9),
      BAIRRO VARCHAR(50),
      CIDADE VARCHAR(50),
      UF VARCHAR(2),
      TELEFONE VARCHAR(15),
      CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
)

select *
from Cliente
